server:
  port: 8083
spring:
  application:
    name: zuul-item
  redis:
    host: 192.168.1.29
    port: 6379
    session:
      store-type: redis
eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api‐a:
      path: /api‐a/**
      serviceId: feign-item
  sensitive-headers:

