server:
  port: 8080
spring:
  application:
    name: eureka-item

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka
