server:
  port: 8081

spring:
  application:
    name: feign-item
  redis:
    host: 192.168.1.29
    port: 6379
    session:
      store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true

MICROSERVICE-ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
